language: node_js
node_js:
  - "node"

cache: npm

script: 
  - npm run build
  - echo "parasite.todack.com" > dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep_history: true
  target_branch: release
  on:
    branch: master