language: node_js
node_js:
  - "14"

cache: npm

script: npm run build

branches:
  only:
    main

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: release
  fqdn: parasite.todack.com
  on:
    branch: main